config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'passwords',
    registrations: 'users',
    sessions: 'sessions',
  }

  get '/address', to: 'addresses#show', as: 'address'
  get '/info_window', to: 'info_window#index', as: 'info_window'
  get '/sitemap', to: 'sitemaps#index', as: 'sitemap'

  scope '/sidebar', controller: :sidebar do
    get :search, as: 'search'
    get :combo_form, as: 'combo_form'
    get :edit_profile, as: 'edit_profile'
  end

  resource :reminders
  resource :things
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root to: 'main#index'
end

app/models/thing.rb
# frozen_string_literal: true

require 'open-uri'
require 'csv'

class Thing < ApplicationRecord
  acts_as_paranoid
  extend Forwardable
  include ActiveModel::ForbiddenAttributesProtection

  VALID_DRAIN_TYPES = ['Storm Water Inlet Drain', 'Catch Basin Drain'].freeze

  belongs_to :user
  def_delegators :reverse_geocode, :city, :country, :country_code,
                 :full_address, :state, :street_address, :street_name,
                 :street_number, :zip
  has_many :reminders, dependent: :destroy
  validates :city_id,
            uniqueness: {scope: :city_domain, message: 'ID should be unique per city'},
            allow_nil: true
  validates :lat, presence: true
  validates :lng, presence: true
  validates :name, obscenity: true

  scope :adopted,
        lambda { |city_domain|
          where(city_domain: city_domain).where.not(user_id: nil)
        }

  scope :for_city,
        lambda { |city_domain|
          where(city_domain: city_domain)
        }

  def self.find_closest(lat, lng, limit = 10, current_city = nil)
    query = <<-SQL
      SELECT *, earth_distance(ll_to_earth(lat, lng), ll_to_earth(?, ?)) as distance
      FROM things
      WHERE deleted_at is NULL
      AND city_domain #{current_city.nil? ? ' IS NULL' : " = '#{current_city}'"}
      ORDER BY distance
      LIMIT ?
    SQL
    find_by_sql([query, lat.to_f, lng.to_f, limit.to_i])
  end

  def display_name
    (adopted? ? adopted_name : name) || ''
  end

  def reverse_geocode
    @reverse_geocode ||= Geokit::Geocoders::MultiGeocoder.reverse_geocode([lat, lng])
  end

  def adopted?
    !user.nil?
  end

  def as_json(options = {})
    super({methods: [:display_name]}.merge(options))
  end
end

app/controllers/things_controller.rb
# frozen_string_literal: true

class ThingsController < ApplicationController
  respond_to :json

  def show
    @things = Thing.find_closest(params[:lat], params[:lng], params[:limit] || 10)
    if @things.blank?
      render(json: {errors: {address: [t('errors.not_found', thing: t('defaults.thing'))]}}, status: :not_found)
    else
      respond_with @things
    end
  end

  def update
    @thing = Thing.find(params[:id])
    if @thing.update(thing_params)
      send_adoption_email(@thing.user, @thing) if @thing.adopted?

      respond_with @thing
    else
      render(json: {errors: @thing.errors}, status: :internal_server_error)
    end
  end

private

  def send_adoption_email(user, thing)
    case user.things.count
    when 1
      ThingMailer.first_adoption_confirmation(thing).deliver_later
    when 2
      ThingMailer.second_adoption_confirmation(thing).deliver_later
    end
  end

  def thing_params
    params.require(:thing).permit(:adopted_name, :user_id)
  end
end

app/views/things/_abandon.html.haml
= form_for :thing, :url => things_path, :method => :put, :html => {:id => "abandon_form"} do |f|
  = f.hidden_field "id"
  = f.hidden_field "user_id", :value => ""
  = f.hidden_field "adopted_name", :value => ""
  %fieldset.form-group
    = f.submit t("buttons.abandon", :thing => t("defaults.thing")), :class => "btn btn-danger btn-block"

app/views/things/_detail.html.haml
- if @thing.priority
  %p
    = t("titles.priority_html", :thing_title  => t("defaults.thing").titlecase, :thing => t("defaults.thing"))
- elsif @thing.system_use_code == 'MS4'
  %p
    %a{href: "http://sfwater.org/index.aspx?page=399", target: '_blank'}
      = t("links.special", :thing => t("defaults.thing"))

app/views/things/adopt.html.haml
%h2
  = t("titles.adopt", :thing => t("defaults.thing").titleize)
= form_for :thing, :url => things_path, :method => :put, :html => {:id => "adoption_form"} do |f|
  = f.hidden_field "id"
  = f.hidden_field "user_id", :value => current_user.id
  %fieldset.form-group
    = f.label "name", t("labels.name_thing", :thing => t("defaults.thing")), :id => "thing_name_label", :class => "control-label"
    = f.text_field "adopted_name", :value => @thing.name, :class => "form-control"
  %fieldset.form-group
    -# buttons.adopt
    = f.submit c("brand.button_adopt").capitalize, :class => "btn btn-primary btn-block"

    -# subjects.update_report
    = f.submit c("brand.update_report"), :class => "btn btn-primary btn-block"

    -# subjects.tagline
    = f.submit c("brand.default_tagline"), :class => "btn btn-primary btn-block"

    -# notices.adopted
    = f.submit c("brand.notices_adopted"), :class => "btn btn-primary btn-block"

    -# titles.adopt 
    = f.submit c("brand.title_adopt"), :class => "btn btn-primary btn-block"

    -# titles.adopted 
    = f.submit c("brand.title_adopted"), :class => "btn btn-primary btn-block"

    -# titles.adopted_tagline 
    = f.submit c("brand.title_adopted_tagline"), :class => "btn btn-primary btn-block"

    -# titles.main 
    = f.submit c("brand.title_main"), :class => "btn btn-primary btn-block"

    -# titles.sign_in 
    = f.submit c("brand.sign_in"), :class => "btn btn-primary btn-block"

    -# titles.email_text 
    = f.submit c("brand.thank_you"), :class => "btn btn-primary btn-block"

    -# titles.email_text 
    = f.submit c("brand.title_email_text"), :class => "btn btn-primary btn-block"

    -# titles.tweet_text 
    = f.submit c("brand.title_tweet_text"), :class => "btn btn-primary btn-block"

    -# titles.description 
    = f.submit c("brand.title_descriptin"), :class => "btn btn-primary btn-block"

  = render partial: 'things/detail'